### ISSUE TITLE
Unable to cast

### ISSUE THREAD

**Issue by basharsaba** [MiRO92/uYou-for-YouTube#441]
Hi,

Suddenly uYou YouTube started to prevent me from casting and it keeps asking to enable Local Network Access which is already enabled.

It happened on all my 3 devices. I restarted them and uninstalled/reinstalled uYou YouTube but it didn’t help.

Casting is working fine from the original YouTube App. 

![IMG_2147](https://github.com/MiRO92/uYou-for-YouTube/assets/45742914/24f7fd42-0d59-4559-804d-56306784f637)
![IMG_2148](https://github.com/MiRO92/uYou-for-YouTube/assets/45742914/7698d9f0-d93a-4ed3-9564-eec6ba87714f)

**Comment by Write** [comment]
Same issue as here : https://github.com/qnblackcat/uYouPlus/issues/1395

**Comment by basharsaba** [comment]
The casting “weirdly” just came back yesterday on all my 3 devices. I never had to do any kind of troubleshooting, reset or update. It just started to work on its own !!!!

However, I found a workaround when the casting wasn’t directly working.  
Go to Settings, General, Watch on TV, AirPlay & Bluetooth devices and click on Link. This will force the AirPlay devices list to open and you can connect to any device from there.

![IMG_2190](https://github.com/MiRO92/uYou-for-YouTube/assets/45742914/a47edd9d-6dbc-4167-bd52-8a4c896dd9ef)

**Comment by Write** [comment]
> The casting “weirdly” just came back yesterday on all my 3 devices. I never had to do any kind of troubleshooting, reset or update. It just started to work on its own !!!!
> 
> However, I found a workaround when the casting wasn’t directly working. Go to Settings, General, Watch on TV, AirPlay & Bluetooth devices and click on Link. This will force the AirPlay devices list to open and you can connect to any device from there.
> 

Still not working for me.

Your workaround only shows Airplay menu and not actual cast devices though. 


I can confirm the bug happens on sideloaded YouTube even without any addons / plugins added.

**Comment by Stavrak2** [comment]
I think I’ve fixed it. Here’s how:

Go to You —> Settings —> A/B —> Enable to show A/B settings (if not already enabled). Reopen YouTube 

again go to You —> Settings —> A/B. In search settings enter ‘local’. Enable the one ending ‘wififixes’ and the one ending ‘reliabilityfixes’. Go back, force close and app and reopen.

Seems to work for me.

**Comment by Write** [comment]
> I think I’ve fixed it. Here’s how:
> 
> 
> 
> Go to You —> Settings —> A/B —> Enable to show A/B settings (if not already enabled). Reopen YouTube 
> 
> 
> 
> again go to You —> Settings —> A/B. In search settings enter ‘local’. Enable the one ending ‘wififixes’ and the one ending ‘reliabilityfixes’. Go back, force close and app and reopen.
> 
> 
> 
> Seems to work for me.

Thanks a lot, it seems to work for me too !

I couldn't find wififixes you mentioned but I just enabled

cxClientEnablelosLocalNetworkPermissionReliabilityFixes

And it works great so far !!

![image](https://github.com/MiRO92/uYou-for-YouTube/assets/541722/e1881440-17b0-4491-b2ac-71db39a008b9)

**Comment by basharsaba** [comment]
Thank you for your input, but I'm unable to find the A/B settings. How do I enable it? 
I'm using YouTube v19.06.2 + uYou v3.0.3 which seems to be the latest.  Do I have to upgrade to a higher version if it exists?

This is what I see when I go to You —> Settings

![IMG_2222](https://github.com/MiRO92/uYou-for-YouTube/assets/45742914/8436e3e0-910f-4ff9-9786-0ce05878f6ec)

**Comment by Write** [comment]
> Thank you for your input, but I'm unable to find the A/B settings. How do I enable it? I'm using YouTube v19.06.2 + uYou v3.0.3 which seems to be the latest. Do I have to upgrade to a higher version if it exists?
> 
> This is what I see when I go to You —> Settings

Well, I mean, you don't have any option I have so IDK. Maybe try uYouEnhanced ?
It supposed to be at the very top


Here's what it looks like for me (but I use uYouEnhanced)

<details><summary>Details</summary>
<p>

![IMAGE 2024-04-17 18:31:37](https://github.com/MiRO92/uYou-for-YouTube/assets/541722/c842a737-19af-4524-8e76-c4fa8d24c568)


</p>
</details>

**Comment by Write** [comment]
> Thank you for your input, but I'm unable to find the A/B settings. How do I enable it? I'm using YouTube v19.06.2 + uYou v3.0.3 which seems to be the latest. Do I have to upgrade to a higher version if it exists?
> 
> This is what I see when I go to You —> Settings
> 
I just built it for you, but please download it fast because I have to remove it : https://github.com/Write/uYouEnhanced/actions/runs/8725539688

**Comment by basharsaba** [comment]
Done. You can remove it. Thank a lot

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by basharsaba** [comment]
Hi again,

The casting has just suddenly stopped on all my devices at the same time although the local network permission is enabled via iPhone settings and A/B. It’s unbelievably weird. I’m dying of curiosity to know how such a thing happens from time to time on all the devices. I think I will just wait and it will come back on its own like last time…. looool 

![IMG_2283](https://github.com/MiRO92/uYou-for-YouTube/assets/45742914/949b3dee-92c5-416e-85a9-bb19892bcbce)

**Comment by Stavrak2** [comment]
Turn off the ‘sockets’ one - that isn’t one of the fixes I mentioned

**Comment by basharsaba** [comment]
You’re right… Only these 2 settings should be enabled... It’s working now… Thanks again.

YTColdConfig.cxClientEnableIosLocalNetworkPermissionReliabilityFixes
YTColdConfig.cxClientEnableIosLocalNetworkPermissionWifiFixes

**Comment by b007zk** [comment]
I have the same problem and for me there's only this setting available:

cxClientEnableIosLocalNetworkPermissionReliabilityFixes

I turned it on and I also turned off cxClientEnableIosLocalNetworkPermissionUsingSockets and it still doesn't work! Not sure what else to try. I'm using uYouPlus-19.08.2-3.0.3

**Comment by Write** [comment]
> I have the same problem and for me there's only this setting available:
> 
> cxClientEnableIosLocalNetworkPermissionReliabilityFixes
> 
> I turned it on and I also turned off cxClientEnableIosLocalNetworkPermissionUsingSockets and it still doesn't work! Not sure what else to try. I'm using uYouPlus-19.08.2-3.0.3

Try this : 

YTColdConfig.cxClientEnableIosLocalNetworkPermissionReliabilityFixes: 1
YTColdConfig.cxClientEnableIosLocalNetworkPermissionUsingSockets: 0
YTColdConfig.cxClientEnableIosLocalNetworkPermissionWifiFixes: 1
YTHotConfig.isPromptForLocalNetworkPermissionsEnabled: 1

**Comment by b007zk** [comment]
Yeah so I forgot to mention in my comment that I also enabled isPromptForLocalNetworkPermissionsEnabled. I also don't have the cxClientEnableIosLocalNetworkPermissionWifiFixes option available.

**Comment by Write** [comment]
> Yeah so I forgot to mention in my comment that I also enabled isPromptForLocalNetworkPermissionsEnabled. I also don't have the cxClientEnableIosLocalNetworkPermissionWifiFixes option available.

Well I can only give you what I use then : 

Total: 9
YTColdConfig.clientInfraClientConfigEnableIosLocalPlaybackSequence2: 1
YTColdConfig.cxClientEnableIosLocalNetworkPermissionReliabilityFixes: 1
YTColdConfig.cxClientEnableIosLocalNetworkPermissionUsingSockets: 0
YTColdConfig.cxClientFallbackToLocalInitialPlaybackDescriptor: 1
YTColdConfig.cxClientSaveCloudScreenInfoInLocalStorageForSmoothPairingOnVerticals: 0
YTColdConfig.enableIosLocalPlaybackSequence: 0
YTColdConfig.isLocalTransportEncryptionEnabled: 1
YTHotConfig.deviceContextOnlySendOnWifi: 1
YTHotConfig.isPromptForLocalNetworkPermissionsEnabled: 0

**Comment by basharsaba** [comment]
Hi,

I usually select videos from uYou+ and cast them directly to my Apple TV, which allows me to watch YouTube ad-free and automatically skip sponsors.

However, as of yesterday, this no longer works. Instead, I see a “🚫” symbol where the playback timer normally appears.

To troubleshoot, I upgraded my Apple TV to iOS 26, but the issue persisted. I then downgraded all four of my iPhone and iPad devices to iOS 18.6.2, performed factory resets, and tested using the official YouTube app, but I continue to encounter the same “🚫” symbol.

I’ve noticed that only a very small number of videos (around 5%) cast successfully, while the remaining 95% fail. The working ones appear to be random and are not tied to any specific category.

Screen mirroring isn’t a workaround either, since opening the YouTube app on the mirrored device causes it to switch back to casting directly from the app.

Could this issue be related to uYou+, or is it likely a change or a bug on YouTube’s side? Are there any A/B settings or adjustments that might resolve it?

Thank you for your support,


![Image](https://github.com/user-attachments/assets/d7c77d4a-d3ee-49e9-ae8f-e3dde39a1462)

**Comment by Stavrak2** [comment]
I’m able to cast directly to my Sony TV by flicking down the control centre and picking the TV from the AirPlay speaker selection. Assuming your TV supports AirPlay this should work, and if it doesn’t, you can do the link via code by turning Wi-Fi off temporarily before pressing the cast button
